### PR TITLE
Completed challenge with updated README.md

### PR DESCRIPTION
**Pull request by colesam**

### CODE REVIEW

**Comment by JeanHules** [comment]
Hey Sam, I am trying to run the scripts and keep getting this error: 

`ERROR: for database  Cannot start service database: b'driver failed programming external connectivity on endpoint prephoops-todo-app_database_1 (bff45739177ac0068c233fc56757f8616ec9e2a84c8beb42cd5217ff413184c6): Error starting userland proxy: Bind for 0.0.0.0:5432 failed: port is already allocated'` 

Not sure if it's a system error on my local machine or what. Maybe I'm just tired and can't think straight. I will try again tomorrow.

**Comment by colesam** [comment]
Good morning John Hull.

That error happened to me last night and it is because there is already a
docker instance of the database (likely all three instances included in the
docker compose) running on your machine. To fix this you need to run the
“down” and “clear” scripts in the scripts directory before running setup
again.

Alternatively you may just have an actual instance of postgresql running on
your computer which is locking up port 5432.

Let me know if I can be more clear.

Sam

**Comment by colesam** [comment]
I also want to mention that if you are running windows, docker will require
different commands. I did my testing on a Linux machine which should be
very similar to Mac.

If docker is being too picky, the app can also be previewed in the usual
way. Just setup the backend/.env file to point to a database of your
choosing and run php artisan serve. Make sure the backend is listening on
port 9000 otherwise you will need to modify the frontend/src/env.js file
with the new address of the api.

**Comment by JeanHules** [comment]
Sure enough some sleep and all is well. got it working right away this morning. Thanks again for the submission.

**Pull request closed without merging**
